### PR TITLE
🐛 Fix issue #38

### LINKED ISSUE #38: User username and discrim are unique
## Describe the bug
The User model username and discrim are unique but they shouldn't be. So, `takos#0001` and `takos#6969` would conflict and even worse, `Biz#6969` and `takos#6969` would also conflict.

## To Reproduce
Create 2 users with the same username or discrim.

## Expected behavior
One of the users isn't created because it conflicts with the other user.

## Additional context
None

### PR DESCRIPTION
**Pull request by takos22**
## Summary

Fix issue #38 
> User username and discrim are unique

## Checklist

- [ ] If endpoints were changed then they have been documented and tested.
    - [ ] I have updated the docmentation to reflect the changes.
    - [ ] I have updated the tests to support the changes.
- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new endpoint or parameter).
- [ ] This PR is a breaking change (e.g. endpoint or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Review by SylteA — CHANGES_REQUESTED** [review]
Username and discriminator need to be unique together, this could be done by making them both primary keys.

I dont think this is possible atm with postDB so my module would need a small change for that.

**Comment by SylteA** [comment]
Nevermind, what I'm asking for works with no errors.

Code used to test:
```py
from postDB import Model, Column, types


class User(Model):
    id = Column(types.Integer(big=True), unique=True)
    username = Column(types.String(length=64), primary_key=True)
    discriminator = Column(types.String(length=4), primary_key=True)


if __name__ == '__main__':
    print(User.create_table_sql(exists_ok=True))
```

**Comment by SylteA** [comment]
bump :eyes:

**Comment by takos22** [comment]
Done 👀

**Review by SylteA — APPROVED** [review]

**Pull request merged**
